POST http://localhost:3333/events
Content-Type: 'application/json'

{
  "title": "NLW Unite",
  "details" : "Um evento para que ama programação",
  "maximumAttendees": 3
}

###

POST http://localhost:3333/events/9e9bd979-9d10-4915-b339-3786b1634f33/attendees
Content-Type: 'application/json'

{
  "name": "Oliveira Caio",
  "email" : "oliveira@nlw.com"
}

###

GET http://localhost:3333/events/9e9bd979-9d10-4915-b339-3786b1634f33

### 

GET http://localhost:3333/attendees/4/badge

### 

GET http://localhost:3333/attendees/5/check-in

### 

GET http://localhost:3333/events/9e9bd979-9d10-4915-b339-3786b1634f33/attendees
# GET http://localhost:3333/events/9e9bd979-9d10-4915-b339-3786b1634f33/attendees?query=césar