POST http://localhost:3333/events
Content-Type: 'application/json'

{
  "title": "NLW Unite",
  "details" : "Um evento para que ama programação",
  "maximumAttendees": 3
}

###

POST http://localhost:3333/events/2665509d-8398-439d-83a8-6093a363ed30/attendees
Content-Type: 'application/json'

{
  "name": "Oliveira Caio",
  "email" : "oliveira@nlw.com"
}

###

GET http://localhost:3333/events/2665509d-8398-439d-83a8-6093a363ed30

### 

GET http://localhost:3333/attendees/4/badge

### 

GET http://localhost:3333/attendees/5/check-in

### 

GET http://localhost:3333/events/2665509d-8398-439d-83a8-6093a363ed30/attendees
# GET http://localhost:3333/events/2665509d-8398-439d-83a8-6093a363ed30/attendees?query=césar